swagger: '2.0'
info:
  description: This is the Swagger definition file for the searcgService for the SOA assignment of Group 9
  version: 1.0.0
  title: SearchApi
host: search
basePath: /api
schemes:
  - http
paths:
  /tracks/search/:
    get:
      summary: Search a single track by song title and artistname
      description: ''
      produces:
        - application/json
      parameters:
        - in: query
          name: title
          type: string
          description: Title of the track
          required: true
        - in: query
          name: artist
          type: string
          description: Artist of the track
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TrackSearchResult'
        '400':
          description: No Search params supplied
          schema: 
            $ref: '#/definitions/Error'
        '502':
          description: Spotifys Answer is wrong
          schema: 
            $ref: '#/definitions/Error'
        '204':
          description: No Tracks found
          schema: 
            $ref: '#/definitions/Error'
        '500':
          description: Generic Error
          schema: 
            $ref: '#/definitions/Error'
  /artists/search/:
    get:
      summary: Search a single artist by its name
      description: ''
      produces:
        - application/json
      parameters:
        - in: query
          name: artist
          type: string
          description: Artistname for Search
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ArtistSearchResult'
        '400':
          description: No Search params supplied
          schema: 
            $ref: '#/definitions/Error'
        '502':
          description: Spotifys Answer is wrong
          schema: 
            $ref: '#/definitions/Error'
        '204':
          description: No Tracks found
          schema: 
            $ref: '#/definitions/Error'
        '500':
          description: Generic Error
          schema: 
            $ref: '#/definitions/Error'
definitions:
  TrackSearchResult:
    type: object
    properties:
      trackId:
        type: string
      artistName:
        type: string
      songTitle:
        type: string
  ArtistSearchResult:
    type: object
    properties:
      artistId:
        type: string
      artistName:
        type: string
  Error:
    type: object
    properties:
      errorMessage:
        type: object
        properties:
          message:
            type: string
