swagger: '2.0'
info:
  description: This is the Swagger definition file for the ChartsService for the SOA assignment of Group 9
  version: 1.0.0
  title: ChartsApi
host: charts
basePath: /api
schemes:
  - http
paths:
  '/charts/{artist-id}':
    get:
      tags:
        - artist
      summary: Get a List of songs
      description: ''
      produces:
        - application/json
      parameters:
        - in: path
          name: artist-id
          description: ID of artists songs to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Songs'
        '400':
          description: Invalid ID supplied
          schema: 
            $ref: '#/definitions/Error'
        '404':
          description: Artist not found
          schema: 
            $ref: '#/definitions/Error'
        '500':
          description: Generic Error
          schema: 
            $ref: '#/definitions/Error'
definitions:
  Songs:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        artist_name:
          type: string
  Error:
    type: object
    properties:
      errorMessage:
        type: object
        properties:
          message:
            type: string
  
