swagger: '2.0'
info:
  description: This is the Swagger definition file for the ImageService for the SOA assignment of Group 9
  version: 1.0.0
  title: ImageApi
host: images
basePath: /api
schemes:
  - http
paths:
  '/cover/{track-id}':
    get:
      summary: Get a cover-url of the provided track-id
      description: ''
      produces:
        - application/json
      parameters:
        - in: path
          name: track-id
          description: ID of the track to getthe cover for
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cover'
        '400':
          description: Invalid ID supplied
          schema: 
            $ref: '#/definitions/Error'
        '404':
          description: Track not found
          schema: 
            $ref: '#/definitions/Error'
        '502':
          description: Spotifys Answer is wrong
          schema: 
            $ref: '#/definitions/Error'
        '204':
          description: No Cover Img
          schema: 
            $ref: '#/definitions/Error'
        '500':
          description: Generic Error
          schema: 
            $ref: '#/definitions/Error'
            
definitions:
  Cover:
    type: object
    properties:
      cover:
        type: object
        properties:
          url:
            type: string
  Error:
    type: object
    properties:
      errorMessage:
        type: object
        properties:
          message:
            type: string
      
